import { Controller } from 'react-hook-form';
import type { Control, UseFormRegister, FieldErrors, FieldValues, Path } from 'react-hook-form';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { UserPicker } from '@/components/shared/UserPicker';

/**
 * Lead Generated by + Created By + Lead Received Date — identical in the New Lead and Edit Lead
 * forms. Both people-pickers always reflect the live set of active Inside Sales users (via
 * UserPicker → /users/assignable), never a hardcoded list, but they're distinct fields:
 * - "Lead Generated by" (`sdrId`) — the SDR who sourced/qualified the lead.
 * - "Created By" (`createdBySdrId`) — a separate, manually-selected attribution (e.g. when an
 *   Admin or a different rep is entering the lead on that SDR's behalf). Not to be confused with
 *   `createdById`, the system-audit field that's always whoever is actually logged in.
 * Lead Received Date defaults to today on creation (see todayDateInputValue in
 * leadFormOptions.ts) and stays freely editable afterward for authorized users.
 */
export function SdrAndReceivedDateFields<
  T extends FieldValues & { sdrId?: string | null; createdBySdrId?: string | null; leadReceivedDate?: string },
>({
  control,
  register,
  errors,
  required = false,
}: {
  control: Control<T>;
  register: UseFormRegister<T>;
  errors?: FieldErrors<T>;
  required?: boolean;
}) {
  const dateError = errors?.leadReceivedDate?.message as string | undefined;
  return (
    <>
      <div className="space-y-1.5">
        <Label>Lead Generated by</Label>
        <Controller
          control={control}
          name={'sdrId' as Path<T>}
          render={({ field }) => (
            <UserPicker value={field.value as string | null} onChange={field.onChange} roles={['INSIDE_SALES']} placeholder="Select SDR…" />
          )}
        />
      </div>
      <div className="space-y-1.5">
        <Label>Created By</Label>
        <Controller
          control={control}
          name={'createdBySdrId' as Path<T>}
          render={({ field }) => (
            <UserPicker value={field.value as string | null} onChange={field.onChange} roles={['INSIDE_SALES']} placeholder="Select SDR…" />
          )}
        />
      </div>
      <div className="space-y-1.5">
        <Label>Lead Received Date{required ? ' *' : ''}</Label>
        <Input type="date" {...register('leadReceivedDate' as Path<T>)} />
        {dateError && <p className="text-xs text-destructive">{dateError}</p>}
      </div>
    </>
  );
}
