import { Router } from 'express';
import { authRouter } from './auth/auth.routes';
import { organizationsRouter } from './organizations/organizations.routes';
import { usersRouter } from './users/users.routes';
import { rolesRouter } from './roles/roles.routes';
import { permissionsRouter } from './permissions/permissions.routes';
import { customFieldsRouter } from './customFields/customFields.routes';
import { pipelineStagesRouter } from './pipelineStages/pipelineStages.routes';
import { customObjectsRouter } from './customObjects/customObjects.routes';
import { savedViewsRouter } from './savedViews/savedViews.routes';
import { validationRulesRouter } from './validationRules/validationRules.routes';
import { duplicatesRouter } from './duplicates/duplicates.routes';
import { companiesRouter } from './companies/companies.routes';
import { contactsRouter } from './contacts/contacts.routes';
import { leadsRouter } from './leads/leads.routes';
import { campaignsRouter } from './campaigns/campaigns.routes';
import { meetingsRouter } from './meetings/meetings.routes';
import { tasksRouter } from './tasks/tasks.routes';
import { casesRouter } from './cases/cases.routes';
import { caseCommentsRouter } from './caseComments/caseComments.routes';
import { knowledgeBaseRouter } from './knowledgeBase/knowledgeBase.routes';
import { documentsRouter } from './documents/documents.routes';
import { commentsRouter } from './comments/comments.routes';
import { notificationsRouter } from './notifications/notifications.routes';
import { activitiesRouter } from './activities/activities.routes';
import { auditLogsRouter } from './auditLogs/auditLogs.routes';
import { dashboardRouter } from './dashboard/dashboard.routes';
import { searchRouter } from './search/search.routes';
import { reportsRouter } from './reports/reports.routes';
import { integrationsRouter } from './integrations/integrations.routes';
import { sequencesRouter } from './sequences/sequences.routes';
import { reportBuilderRouter } from './reportBuilder/reportBuilder.routes';
import { dashboardWidgetsRouter } from './dashboardWidgets/dashboardWidgets.routes';
import { apiKeysRouter } from './apiKeys/apiKeys.routes';
import { webhooksRouter } from './webhooks/webhooks.routes';
import { connectorsRouter } from './connectors/connectors.routes';
import { billingRouter } from './billing/billing.routes';
import { platformAdminRouter } from './platformAdmin/platformAdmin.routes';
import { aiRouter } from './ai/ai.routes';
import { ipAllowlistRouter } from './ipAllowlist/ipAllowlist.routes';

export const apiRouter = Router();

apiRouter.use('/auth', authRouter);
apiRouter.use('/organizations', organizationsRouter);
apiRouter.use('/users', usersRouter);
apiRouter.use('/roles', rolesRouter);
apiRouter.use('/permissions', permissionsRouter);
apiRouter.use('/custom-fields', customFieldsRouter);
apiRouter.use('/pipeline-stages', pipelineStagesRouter);
apiRouter.use('/custom-objects', customObjectsRouter);
apiRouter.use('/saved-views', savedViewsRouter);
apiRouter.use('/validation-rules', validationRulesRouter);
apiRouter.use('/duplicates', duplicatesRouter);
apiRouter.use('/companies', companiesRouter);
apiRouter.use('/contacts', contactsRouter);
apiRouter.use('/leads', leadsRouter);
apiRouter.use('/campaigns', campaignsRouter);
apiRouter.use('/meetings', meetingsRouter);
apiRouter.use('/tasks', tasksRouter);
apiRouter.use('/cases', casesRouter);
apiRouter.use('/case-comments', caseCommentsRouter);
apiRouter.use('/knowledge-base', knowledgeBaseRouter);
apiRouter.use('/documents', documentsRouter);
apiRouter.use('/comments', commentsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/activities', activitiesRouter);
apiRouter.use('/audit-logs', auditLogsRouter);
apiRouter.use('/dashboard', dashboardRouter);
apiRouter.use('/search', searchRouter);
apiRouter.use('/reports', reportsRouter);
apiRouter.use('/integrations', integrationsRouter);
apiRouter.use('/sequences', sequencesRouter);
apiRouter.use('/custom-reports', reportBuilderRouter);
apiRouter.use('/dashboard-widgets', dashboardWidgetsRouter);
apiRouter.use('/api-keys', apiKeysRouter);
apiRouter.use('/webhooks', webhooksRouter);
apiRouter.use('/connectors', connectorsRouter);
apiRouter.use('/billing', billingRouter);
apiRouter.use('/platform-admin', platformAdminRouter);
apiRouter.use('/ai', aiRouter);
apiRouter.use('/ip-allowlist', ipAllowlistRouter);
